### PR TITLE
[Feature] Ability to build anonymous relationships

### PR DESCRIPTION
**Pull request by jonnii**
Adds a static `Relationship` class to you can create relationships from
anonymous types:

```
var relationship = Relationship.Create(new
  {
     id = "bobby",
     type = "bandit"
  }
);
```

### CODE REVIEW

**Comment by jonnii** [comment]
@codecutout we use anonymous types quite heavily when modelling our APIs, which is awkward when using anonymous types. This is a good work around as the type can be inferred statically, but not when it's a constructor argument (unfortunately).

**Comment by jonnii** [comment]
We probably also need one of these for `DocumentRoot`.

**Comment by alex-davies** [comment]
@jonnii you should already be able to create relationships with anonymous types directly

```csharp
        [Fact]
        public void When_anonymous_types_should_serialize()
        {
            var root = new
            {
                Id = "hq",
                Type = "Theives-Guild",
                Leader = new
                {
                    Id = "bobby",
                    Type = "Bandit",
                    Hobbies = new[] { "croquet" }
                }
            };

            var json = JsonConvert.SerializeObject(root, settings);
            var expectedjson = @"
{
  ""data"": {
    ""id"": ""hq"",
    ""type"": ""Theives-Guild"",
    ""relationships"": {
      ""leader"": {
        ""data"": {
          ""id"": ""bobby"",
          ""type"": ""Bandit""
        }
      }
    }
  },
  ""included"": [
    {
      ""id"": ""bobby"",
      ""type"": ""Bandit"",
      ""attributes"": {
        ""hobbies"": [
          ""croquet""
        ]
      }
    }
  ]
}";
            Assert.Equal(json, expectedjson, JsonStringEqualityComparer.Instance);
        }
```

The `Relationship` class is only a convenience class if you want to include the optional `meta` or `links` properties that relate to the relationship rather than the resource (http://jsonapi.org/format/#document-resource-object-relationships)

**Comment by jonnii** [comment]
@codecutout I need it specifically for the links as we include the related link on the response so ember data does the right thing.

**Comment by alex-davies** [comment]
I should also point you you also don't need to use the Relationship<> object at all, you can get away with doing the whole relationship as anonymous. The only special interfaces the serialiser actually cares about are in `JsonApiSerializer.JsonApi.WellKnown` the others are just convenience when creating object models

```csharp
var root = new
{
    Id = "hq",
    Type = "Theives-Guild",
    Leader = new
    {
        Links = new Links
        {
            { "self", new Link(){ Href = "http://theives/hq/leader" } }
        },
        Data = new
        {
            Id = "bobby",
            Type = "Bandit",
            Hobbies = new[] { "croquet" }
        }
    }
                
};
```

**Comment by alex-davies** [comment]
Although i'm not against adding convenience constructor methods and can especially see the usefulness in the document root. Just trying to see if there was an easier way to do what you were trying to achieve.

Before merging could you 
1. Add similar method for document root (see little point having document root create as a separate release)
2. Add xml comments (doesn't have to be too elaborate)
3. Bump the minor package version, assembly version and assembly file version from within the csproj (public interface change so need a new version)

**Comment by jonnii** [comment]
@codecutout will do. How do you feel about moving to something like [GitVersion](https://gitversion.readthedocs.io/en/latest/)? It uses git tags and I think affords a bit more control on how/when a new version is released. In the mean time i'll follow your instructions.

**Comment by jonnii** [comment]
> I should also point you you also don't need to use the Relationship<> object at all, you can get away with doing the whole relationship as anonymous.

Good to know. I think that's actually a much better approach, thanks!

**Comment by jonnii** [comment]
@codecutout done - let me know if you want any other changes.

**Pull request merged**
