### PR TITLE
Serialization refactoring

### PR DESCRIPTION
**Pull request by alex-davies**
Changes involved
* Add `ResourceRelationshipConverter` to allow easier identification of relationships without any data
* Significant clean up the `ResourceObjectConvertor` logic removing the dependency on probes.
* Relationship/Attribute distinction is now done up front removing necessity of `JsonWriterCapture`
* Add non generic `Relationship` to allow definition of relationship with data (e.g. only links)
* Add checks that will throw an error if a explicitly defined relationship or document-root does not contain resource objects

Features this allows
* It is now possible to define dataless relationships. previously relationships had to have a null data now it is possible not to define one at all
```csharp
            var root = new Article
            {
                Id = "1234",
                Title = "My Article",
                Comments = new Relationship //new non-generic relationship
                {
                    //No Data property define and no value is serialized out
                    Links = new Links
                    {
                        { "related", new Link {  Href = "http://example.com/articles/1/comments" } }
                    }
                }
            };
```
* `object[]` type relationships can be serialized. Previously it was impossible to serialize an `object[]` as a relationship, you first needed to cast it into `SomeTypeWithAnId[]`, this made mixed type arrays difficult to serialize. Now as long as you specify the list in a relationship object it will attempt to serialize all objects as resource objects. Note that deserialization still requires `Type` information and will still be unable to deserialize `object` types
```csharp
            var article = new
            {
                Id = "1234",
                Type = "articles",
                Title = "My Article",
                Comments = new
                {
                    Data = new object[] {
                        new Comment() { Id = "c1", Body="Regular comment" },
                        new { Id = "c2", Type = "moderator-comments", Body="Special moderator comment" },
                   }
                }
            };
```

### CODE REVIEW

**Comment by alex-davies** [comment]
@jonnii this should include the two features you were looking for.

Could you confirm that this version resolves your issues (I know you are already building from the source, but let me know if you want me to publish a beta version for easier testing). Once you confirm that this solves your problems and doesn't generate any new ones ill merge to master and publish a stable release.

Because of the large scope of changes I am being a little more more cautious for this release than I have for previous releases

**Comment by jonnii** [comment]
@codecutout I'll give this a whirl and report back - in the mean time I think we should bring the test from here over? https://github.com/codecutout/JsonApiSerializer/pull/52 I think it has value (the one that serializes an object array).

**Comment by jonnii** [comment]
@codecutout i tried it - i do not believe it is fixed.

**Comment by alex-davies** [comment]
@jonnii which part are you not seeing fixed the dataless relationship or the `object` relationships

for dataless relationships either put it in a `Relationship` object (no generics and no data element) or make an anonymous object with no `data` property. We need this to distinguish null/empty array data from no data
* https://github.com/codecutout/JsonApiSerializer/pull/53/files#diff-131eb50d849242460f43df2783c257c5R442

for `object` relationshps  you will need to either make them explicitly in a document root, or explicitly in a relationship. This is the easiest way to determine that the object is intended to be a relationship rather than an attribute
* https://github.com/codecutout/JsonApiSerializer/pull/53/files#diff-6d91d8f81ff23bc817afcbb39ca5f477R214
* https://github.com/codecutout/JsonApiSerializer/pull/53/files#diff-131eb50d849242460f43df2783c257c5R146

(technically for the document root we could also know they are all document objects, but in order to do that we need to take full control of all serialization for all arrays away from json.net. This gives lots of issues for both serialisation and deserialization)

**Comment by jonnii** [comment]
> for object relationshps you will need to either make them explicitly in a document root, or explicitly in a relationship

I'm totally fine with that choice if this is the direction you'd like to go - I think it should at least be documented as i would have expected an array of objects to serialize the same way as types.

**Comment by jonnii** [comment]
@codecutout i think regardless lets merge this _as is_ and then we re-evaluate that decision if anyone else finds it surprising, but I'm ok with having to be specific about a document root in my applications.

**Comment by alex-davies** [comment]
> i would have expected an array of objects to serialize the same way as types.

In a way they do

If we have an property `object Author` that is null there is no way to know to know if its an attribute or relationship. We will end up assuming an attribute. If it has a value we use the value's type (e.g. `Author`) to determine if is a relationship or attribute

if we have a property `IEnumerable<object> Comments` that is null, there is no way to know if its an attribute or relationship. We need up assuming an attribute. If we have a value we use the value's type (e.g `IEnumerable<Comment>`)  to determine if its a list of relationships or a list of attributes

Ultimately both null `object`/`IEnumerable<object>` situations are not great because if its null they end up being an attribute, if they are populated they may end up being a relationship.

My initial thought was to use the items within the array to determine if its a relationship or not, but this leads to the case when we have an empty array we do not know whether its a relationship or not, so end up using it as an attribute. This falls into the same problem with nulls in that it moves between relationships/attributes depending on data, except that this is a fairly common case where we have empty arrays purely due to data

The way to avoid this is either define the properties with the correct types (this should be case most of the time as most .net languages strongly encourage this anyway). Alternatively if you define the object in an explicit relationship then we know that its a relationship so can handle it as such.

**Pull request merged**
