### PR TITLE
serialization performance

### PR DESCRIPTION
**Pull request by alex-davies**

### CODE REVIEW

**Comment by alex-davies** [comment]
Benchmark performance as fraction of standard json serialization
**Without these changes:**  0.35 
**changes from #77:** 0.48
**All these changes:** 0.71

**Comment by jonnii** [comment]
Awesome! What did you find were the next big wins?

**Comment by alex-davies** [comment]
Most of the improvement was using a `ResourceObjectContract` that predetermines the json:api properties. So the `WriteFullObjectJson` and `WriteReferenceObjectJson` no longer needs to to do property lookups or determine if a property is an attribute or relationship, this is all contained in the `ResourceObjectContract` which json.net will cache for us.

Also a small change at https://github.com/codecutout/JsonApiSerializer/pull/79/files#diff-b1866ec017b021bc4857b4ee4f7a36a7R48 saw a rather nice performance bump

There are a few other things I want to have a look into
* Tune the list processing to remove the ienumerable
* Investigate a way remove dependance on `writer.path` which is starting to show up more during profiling. We may be able to keep our own writing `stack` to determine if we are in a relationship or not. But i'm not sure if the stack will be any faster than the `writer.path`

**Comment by jonnii** [comment]
Want to get this in and we can do another round later? This will be pretty dramatic as is.

**Comment by alex-davies** [comment]
**With the latest commit:** 1.02

You read that correctly, it is somehow faster than vanilla json serialisation.

I'm ecstatic about the speed, but it is making me question my benchmark. I cant see any obvious issue with it, all tests are passing and it is undoubtedly faster (although i'm still suspicious its THAT much faster) so I cant see any reason to not merge it in

**Comment by jonnii** [comment]
Awesome! 👍 Nice work :D

**Pull request merged**
