### PR TITLE
[Refactor] Things as I read

### PR DESCRIPTION
**Pull request by jonnii**
* Removes some uses of `this` that are not necessary
 * Removes some extra whitespace
 * Uses some C# 7 features
 * Removes the `build` folder in the solution (seems unused)

### CODE REVIEW

**Comment by jonnii** [comment]
@codecutout just trying to boyscout as I read and figure out how everything is put together. Feel free to close this PR, or if you can give me some guidance as to coding style, or what you expect I'm happy to follow any guidelines.

**Comment by alex-davies** [comment]
@jonnii out of curiosity what c# lint tool are you using for these changes?

 * The C# 7 ones I have incorporated into https://github.com/codecutout/JsonApiSerializer/pull/53. 
 * The spacing changes i'm not too concerned about, but if I were to put them in it is probably easier to have a single commit that applies it to the entire project

**Comment by jonnii** [comment]
@codecutout I'm using reshaper - if you have an open source project you can get a free license (https://www.jetbrains.com/buy/opensource/).

**Comment by jonnii** [comment]
@codecutout i did some more - I'm not sure it's a good idea to apply to this to the whole solution, it will touch _a lot_ of files.

**Comment by alex-davies** [comment]
This is now out of date and as the changes were minor syntax changes it is now worth the hassle of rebasing. 

These changes are probably better to occur when feautures/fixes require you to touch those bits of the code

**Pull request closed without merging**
