### PR TITLE
Relationships not serialized correctly

### PR DESCRIPTION
**Pull request by jonnii**
Here's a fun one. This was working before the performance changes. It's likely something to do with detecting if something is a relationship or not.

### CODE REVIEW

**Comment by alex-davies** [comment]
Hmm, its because we determined upfront if properties were relationships. THis means we could only use hte declared type, not the actual object type.

Might have to put something in place to check attributes are not relationships during the serialization

Thanks for catching this

**Comment by alex-davies** [comment]
Needs to be fixed so that we match previous behaviour. Dont want to break any existing users

But should be noted i'm not too keen on the runtime type checking for attribute/relationships. It leads to odd cases with null. For example in the following
```
var article1 = new
{
    id = "1234",
    type = "articles",
    author = (object)new
    {
        Id = "333",
        type = "people",
        FirstName = "John",
        LastName = "Smith",
        Twitter = "jsmi"
    },
};

var article2 = new
{
    id = "1234",
    type = "articles",
    author = (object)null
};
```
`article1` has an author so it is a relationship. But if the author happens to be null (like in `article2`) then author is suddenly an attribute. Having a property change from a relationship to an attribute depending on if its null is unexpected behaviour

**Comment by jonnii** [comment]
Yeah, this is not ideal for sure. When using anonymous types it would be good for us to encourage using the "special" classes, like `Relationship<T>` and friends. It's less ambiguous and the type hints can mean we can do the special tricks. 

Thanks for getting his fixed, I'll give this a try and report back.

**Comment by jonnii** [comment]
This fix works great. Thanks!

**Pull request merged**
