### PR TITLE
Respect property null value handling

### PR DESCRIPTION
**Pull request by alarkvell**
Take into account NullValueHandling on each property:
```csharp
    public class Article
    {
        public string Type { get; set; } = "articles";

        public string Id { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Include)]
        public string Title { get; set; }
    }
```

### CODE REVIEW

**Comment by alex-davies** [comment]
Good change. I wasnt even aware you could the null handling was configurable at a property level. 

Ill write some unit tests to go along with it and release a new version

**Comment by alex-davies** [comment]
I have also simplified the if conditions down to 

```csharp
if (propValue == null && (prop.NullValueHandling ?? serializer.NullValueHandling) == NullValueHandling.Ignore)
                    continue;
```

**Comment by alex-davies** [comment]
@alarkvell I have released this as 1.0.0

Change wouldn't normally be a major version bump, but wanted to get the library out of the 0.x.x versions as it is being used elsewhere in production systems

**Comment by alarkvell** [comment]
Thank you for the improvements!
And bumping to 1.0.0 is also nice :+1: Would you like to create releases or tags in GitHub?

**Pull request merged**
