### PR TITLE
[Refactor] Remove unused usings

### PR DESCRIPTION
**Pull request by jonnii**
* Removes unused usings
* Renames `ILinkcs.cs` to `ILink.cs`

### CODE REVIEW

**Comment by jonnii** [comment]
@codecutout Are you open to these kinds of refactoring PRs? I know some people find them annoying - so want to check before I do any others.

**Comment by alex-davies** [comment]
@jonnii thanks for contributing, and thanks for asking about refactoring PR's. In general i'm more than happy to accept PRs, as for this specific one
* Renaming of ILinkcs.cs is worthwhile and happy to get those kind of fixes in
* I'm normally ambivalent towards removing unused `using`s , they do no harm being there and I generally don't spend any time reading a files using statements to care. But as you have done them ill merge it in

Ill merge but wont publish a release as there is no functional change. 

If you do any future PRs with bug fix or functional change could you also bump the semver number on the project as well, this will allow the CI tooling to publish a new version of the package

Thanks

**Comment by jonnii** [comment]
@codecutout will do!

**Comment by jonnii** [comment]
Just out of interest when you say:

> If you do any future PRs with bug fix or functional change could you also bump the semver number on the project as well, this will allow the CI tooling to publish a new version of the package

Do you mean bumping the version in the `csproj`?

**Pull request merged**
