### PR TITLE
Large refactor to allow support of identifier objects

### PR DESCRIPTION
**Pull request by alex-davies**
* Large refactoring of serialization/deserialization
* Processing resource objects relationship will now always go through ResourceObjectConverter->RelationshipObjectConverter->ResourceObjectConverter
* Each converter handles only its part of the process, but can process multiple different inputs
* Can now support custom Identifier objects

### CODE REVIEW

**Comment by alex-davies** [comment]
@jonnii here is a version that allows custom resource objects that implement `IResourceIdentifier<>`

I did go on a bit of a refactoring spree and made split the logic out into three distinct converters which always get called when processing relationships
* `ResourceObjectConverter` - called for the full object
* `ResoruceRelationshipConverter` - call for all relationships
* `ResourceIdentityConverter` -called for all resource identities

Overall this model splits up the logic more nicely and the `ResourceObjectConverter` does not need to know how to process both full objects and object references. 

Unfortunately I needed to do a lot of hacks to ensure it remains backward compatible for defining custom `ResourceObjectConverters` (for purposes of overriding object creation). Not sure I like these hacks, but it might be something I live with until I do breaking change release where I can change how object creation is configured.

Still would like to put a bit more testing around it and need to update readme, but if you are welcome to try it out and see if it solves your issue

**Comment by jonnii** [comment]
Would you be able to publish a `pre` release? If so I'm happy to try it in prod and see how it goes.

**Comment by jonnii** [comment]
@alex-davies would you accept a PR which adds something like [GitVersion](https://gitversion.readthedocs.io/en/latest/) and a move to a tag based release process using the github releases feature? I've had a really good experience with GitVersion myself (including on appveyor).

**Comment by alex-davies** [comment]
> would you accept a PR which adds something like GitVersion and a move to a tag based release process using the github releases feature?

I'm not against it, but it is not something i'm really that concerned with. The current process of keeping the version in the proj file is simple, works fine and hasn't really caused me many headaches

**Comment by alex-davies** [comment]
I have fixed a few more backward comparability issues. Again most of these fixes a bit hacky but will live with them until 2.0

@jonnii I have released a beta version (https://www.nuget.org/packages/JsonApiSerializer/1.6.0-beta01) feel free to try it out and see if it fulfils your needs

**Comment by jonnii** [comment]
Will give this a whirl tomorrow! Thanks!

**Comment by jonnii** [comment]
> I'm not against it, but it is not something i'm really that concerned with. The current process of keeping the version in the proj file is simple, works fine and hasn't really caused me many headaches

The benefit is it makes generating the version really easy and consistent and if you wanted to be able to release a branch (for example) it'll tag everything correctly with the SHA and the branch name.

**Comment by jonnii** [comment]
@alex-davies Everything seems to check out with the beta package will do more testing today. Maybe now is a good time to make the breaking changes? What else would you want to get into `2.0`?

**Comment by jonnii** [comment]
@alex-davies anything I can do to help here?

**Comment by alex-davies** [comment]
@jonnii if everything is fine ill promote to 1.6

The breaking change in 2.0 is more about changing how some of the customisation are provided and care needs to be taken to make sure the same functionality is offered, even if it is configured in a different way.

**Pull request merged**
